INPUT_FILE_NAME = 'input'
READONLY = 'r'
PORT = 3005
HOST = '127.0.0.1'
BUFFER_SIZE = 1024 #for example
ERROR = 'error'
AT_EXIT = 'at_exit'
OUTPUT_FILE_NAME = 'output'
OVERWRITE = 'w+'
MAX_PORTS = 2
EXTENSION = 'bin'
TIMEOUT = 5